[book]
title = "orb li"
authors = ["orb li"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/orbli/orbli"
cname = "orbb.li"
mathjax-support = true